[tool.poetry]
name = "PtpUploader"
version = "0.9.0"
description = "A small uploader for a mildly popular movie site"
authors = ["kannibalox <kannibalox@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.8.0,<4.0"
requests = "^2.26.0"
Django = "^3.2.8"
pyrosimple = "^1.0.0"
guessit = "^3.3.1"
imdbpy = {git = "https://github.com/alberanid/imdbpy"}

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
